
DROP TABLE IF EXISTS [StockDetail]
DROP TABLE IF EXISTS [Product];
DROP TABLE IF EXISTS [User];
DROP TABLE IF EXISTS [Stock];

DROP TABLE IF EXISTS City;
DROP TABLE IF EXISTS Province;
DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS  [User1];




